import type {
  Agent,
  CategoryPoint,
  DashboardData,
  Insight,
  KPI,
  Lead,
  TimeseriesPoint,
  User,
  Workflow,
} from "./types";

const user: User = {
  id: "u_001",
  name: "Mike Gonzalez",
  initials: "MG",
  role: "Team Leader",
  email: "mike@gonzalezteam.com",
  teamName: "Gonzalez Team",
};

const period = {
  start: "2026-04-21",
  end: "2026-04-27",
  label: "Apr 21 – 27, 2026",
};

const kpis: KPI[] = [
  {
    id: "active-deals",
    label: "Active Deals",
    value: "47",
    rawValue: 47,
    hint: "$14.2M pipeline",
    iconKey: "deals",
    tone: "primary",
    trend: [38, 41, 39, 43, 45, 44, 47, 47],
    delta: { value: 12.4, period: "vs last week" },
  },
  {
    id: "new-leads",
    label: "New Leads",
    value: "89",
    rawValue: 89,
    hint: "this week",
    iconKey: "leads",
    tone: "success",
    trend: [72, 76, 79, 82, 85, 84, 87, 89],
    delta: { value: 8.1, period: "vs last week" },
  },
  {
    id: "lead-to-appt",
    label: "Lead to Appointment",
    value: "18.4%",
    rawValue: 18.4,
    hint: "30-day rolling",
    iconKey: "appointment",
    tone: "warning",
    trend: [20.1, 19.4, 19.2, 19.0, 18.9, 18.6, 18.5, 18.4],
    delta: { value: -2.1, period: "vs last month" },
  },
  {
    id: "response-time",
    label: "Avg Response Time",
    value: "3m 22s",
    rawValue: 202,
    hint: "first touch",
    iconKey: "response-time",
    tone: "danger",
    trend: [5.8, 5.4, 5.0, 4.7, 4.5, 4.2, 3.6, 3.4],
    delta: { value: -40.2, period: "vs last week", inverted: true },
  },
];

const pipelineTrend: TimeseriesPoint[] = [
  { label: "Feb 03", value: 9_800_000 },
  { label: "Feb 10", value: 10_400_000 },
  { label: "Feb 17", value: 10_100_000 },
  { label: "Feb 24", value: 11_200_000 },
  { label: "Mar 03", value: 10_800_000 },
  { label: "Mar 10", value: 11_900_000 },
  { label: "Mar 17", value: 12_400_000 },
  { label: "Mar 24", value: 11_700_000 },
  { label: "Mar 31", value: 12_800_000 },
  { label: "Apr 07", value: 13_500_000 },
  { label: "Apr 14", value: 13_100_000 },
  { label: "Apr 21", value: 14_200_000 },
];

const leadsBySource: CategoryPoint[] = [
  { label: "Zillow Premier", value: 28 },
  { label: "Follow Up Boss", value: 22 },
  { label: "Google Ads", value: 14 },
  { label: "Realtor.com", value: 11 },
  { label: "BombBomb", value: 8 },
  { label: "Mailchimp", value: 6 },
];

const teamProductionTrend: TimeseriesPoint[] = [
  { label: "Feb 03", value: 1 },
  { label: "Feb 10", value: 2 },
  { label: "Feb 17", value: 3 },
  { label: "Feb 24", value: 2 },
  { label: "Mar 03", value: 3 },
  { label: "Mar 10", value: 2 },
  { label: "Mar 17", value: 3 },
  { label: "Mar 24", value: 4 },
  { label: "Mar 31", value: 3 },
  { label: "Apr 07", value: 5 },
  { label: "Apr 14", value: 4 },
  { label: "Apr 21", value: 6 },
];

const completionRateTrend: TimeseriesPoint[] = [
  { label: "Feb 03", value: 88.2 },
  { label: "Feb 10", value: 89.1 },
  { label: "Feb 17", value: 87.4 },
  { label: "Feb 24", value: 90.3 },
  { label: "Mar 03", value: 88.9 },
  { label: "Mar 10", value: 91.2 },
  { label: "Mar 17", value: 89.6 },
  { label: "Mar 24", value: 86.4 },
  { label: "Mar 31", value: 82.1 },
  { label: "Apr 07", value: 78.5 },
  { label: "Apr 14", value: 75.2 },
  { label: "Apr 21", value: 71.8 },
];

const pipelineByStage: CategoryPoint[] = [
  { label: "New", value: 18, secondary: 5_400_000, color: "#94a3b8" },
  { label: "Qualified", value: 12, secondary: 3_600_000, color: "#0ea5e9" },
  { label: "Appointment Set", value: 8, secondary: 2_400_000, color: "#f59e0b" },
  { label: "Showing", value: 5, secondary: 1_500_000, color: "#7c3aed" },
  { label: "Offer", value: 3, secondary: 900_000, color: "#10b981" },
  { label: "Under Contract", value: 1, secondary: 400_000, color: "#059669" },
];

const agents: Agent[] = [
  {
    id: "a_001",
    name: "Sarah Mitchell",
    initials: "SM",
    avatarColor: "bg-violet-500",
    role: "Listing Agent",
    joinedAt: "2021-03-15",
    metrics: {
      dealsClosedYTD: 8,
      volumeClosedYTD: 2_410_000,
      activeDeals: 11,
      pipelineValue: 3_850_000,
      leadsThisMonth: 24,
      appointmentsSet: 9,
      conversionRate: 22.4,
      avgResponseMinutes: 4,
    },
    trend: [3, 5, 4, 6, 7, 5, 8, 8],
    status: "top",
    aiAdoptionScore: 92,
    aiTip: "Top of the team — keep your speed-to-lead going.",
    avatarUrl: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: "a_002",
    name: "James Carter",
    initials: "JC",
    avatarColor: "bg-emerald-500",
    role: "Buyer's Agent",
    joinedAt: "2020-08-02",
    metrics: {
      dealsClosedYTD: 7,
      volumeClosedYTD: 2_120_000,
      activeDeals: 9,
      pipelineValue: 2_940_000,
      leadsThisMonth: 19,
      appointmentsSet: 7,
      conversionRate: 19.1,
      avgResponseMinutes: 6,
    },
    trend: [4, 4, 5, 6, 5, 7, 6, 7],
    status: "steady",
    aiAdoptionScore: 76,
    aiTip: "Try BombBomb video for warmer demo conversion.",
    avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: "a_003",
    name: "Priya Shah",
    initials: "PS",
    avatarColor: "bg-amber-500",
    role: "Dual",
    joinedAt: "2022-01-20",
    metrics: {
      dealsClosedYTD: 6,
      volumeClosedYTD: 1_840_000,
      activeDeals: 8,
      pipelineValue: 2_310_000,
      leadsThisMonth: 17,
      appointmentsSet: 8,
      conversionRate: 24.0,
      avgResponseMinutes: 3,
    },
    trend: [2, 3, 4, 5, 5, 6, 6, 6],
    status: "rising",
    aiAdoptionScore: 88,
    aiTip: "Queue at 2× capacity — rebalance some leads.",
    avatarUrl: "https://randomuser.me/api/portraits/women/68.jpg",
  },
  {
    id: "a_004",
    name: "Marcus Reyes",
    initials: "MR",
    avatarColor: "bg-sky-500",
    role: "Buyer's Agent",
    joinedAt: "2019-11-04",
    metrics: {
      dealsClosedYTD: 5,
      volumeClosedYTD: 1_510_000,
      activeDeals: 7,
      pipelineValue: 2_080_000,
      leadsThisMonth: 14,
      appointmentsSet: 5,
      conversionRate: 16.0,
      avgResponseMinutes: 8,
    },
    trend: [5, 4, 4, 6, 5, 4, 5, 5],
    status: "steady",
    aiAdoptionScore: 64,
    aiTip: "Adopt the 5-min SMS workflow for biggest ROI lift.",
    avatarUrl: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: "a_005",
    name: "Emma O'Brien",
    initials: "EO",
    avatarColor: "bg-rose-500",
    role: "Listing Agent",
    joinedAt: "2018-06-12",
    metrics: {
      dealsClosedYTD: 5,
      volumeClosedYTD: 1_390_000,
      activeDeals: 6,
      pipelineValue: 1_780_000,
      leadsThisMonth: 12,
      appointmentsSet: 4,
      conversionRate: 14.2,
      avgResponseMinutes: 11,
    },
    trend: [6, 6, 5, 4, 4, 4, 5, 5],
    status: "needs-coaching",
    coachingNote:
      "Response time slipped above 10 min — review BombBomb cadence and lead routing.",
    aiAdoptionScore: 42,
    aiTip: "Response time critical — start with Calendly defaults.",
    avatarUrl: "https://randomuser.me/api/portraits/women/79.jpg",
  },
  {
    id: "a_006",
    name: "Daniel Park",
    initials: "DP",
    avatarColor: "bg-teal-500",
    role: "Junior Agent",
    joinedAt: "2024-09-01",
    metrics: {
      dealsClosedYTD: 3,
      volumeClosedYTD: 820_000,
      activeDeals: 5,
      pipelineValue: 1_240_000,
      leadsThisMonth: 11,
      appointmentsSet: 4,
      conversionRate: 17.5,
      avgResponseMinutes: 5,
    },
    trend: [1, 2, 2, 3, 3, 3, 3, 3],
    status: "rising",
    aiAdoptionScore: 71,
    aiTip: "Solid ramp — add BombBomb to your follow-up cadence.",
    avatarUrl: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  // ───── 24 additional agents (30 total) ─────
  {
    id: "a_007",
    name: "Aisha Patel",
    initials: "AP",
    avatarColor: "bg-purple-500",
    role: "Listing Agent",
    joinedAt: "2017-04-10",
    metrics: { dealsClosedYTD: 9, volumeClosedYTD: 2_810_000, activeDeals: 12, pipelineValue: 4_120_000, leadsThisMonth: 26, appointmentsSet: 11, conversionRate: 25.1, avgResponseMinutes: 3 },
    trend: [4, 5, 5, 6, 7, 6, 8, 9],
    status: "top",
    aiAdoptionScore: 95,
    aiTip: "Best-in-class adoption — mentor the new hires.",
    avatarUrl: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: "a_008",
    name: "Tyler Brennan",
    initials: "TB",
    avatarColor: "bg-blue-500",
    role: "Buyer's Agent",
    joinedAt: "2019-07-22",
    metrics: { dealsClosedYTD: 6, volumeClosedYTD: 1_720_000, activeDeals: 8, pipelineValue: 2_460_000, leadsThisMonth: 16, appointmentsSet: 6, conversionRate: 18.3, avgResponseMinutes: 6 },
    trend: [3, 4, 4, 5, 5, 4, 5, 6],
    status: "steady",
    aiAdoptionScore: 73,
    aiTip: "Try the Zillow speed-to-lead workflow this week.",
    avatarUrl: "https://randomuser.me/api/portraits/men/41.jpg",
  },
  {
    id: "a_009",
    name: "Madison Lee",
    initials: "ML",
    avatarColor: "bg-pink-500",
    role: "Listing Agent",
    joinedAt: "2018-09-15",
    metrics: { dealsClosedYTD: 7, volumeClosedYTD: 2_240_000, activeDeals: 9, pipelineValue: 3_010_000, leadsThisMonth: 18, appointmentsSet: 8, conversionRate: 21.7, avgResponseMinutes: 4 },
    trend: [4, 5, 6, 5, 7, 6, 7, 7],
    status: "rising",
    aiAdoptionScore: 84,
    aiTip: "Excellent run — keep the BombBomb cadence going.",
    avatarUrl: "https://randomuser.me/api/portraits/women/33.jpg",
  },
  {
    id: "a_010",
    name: "Connor Reilly",
    initials: "CR",
    avatarColor: "bg-cyan-500",
    role: "Junior Agent",
    joinedAt: "2025-02-03",
    metrics: { dealsClosedYTD: 2, volumeClosedYTD: 540_000, activeDeals: 4, pipelineValue: 980_000, leadsThisMonth: 9, appointmentsSet: 3, conversionRate: 14.8, avgResponseMinutes: 7 },
    trend: [0, 1, 1, 2, 2, 2, 3, 2],
    status: "rising",
    aiAdoptionScore: 58,
    aiTip: "Adopt one workflow per week — start with speed-to-lead.",
    avatarUrl: "https://randomuser.me/api/portraits/men/57.jpg",
  },
  {
    id: "a_011",
    name: "Olivia Tran",
    initials: "OT",
    avatarColor: "bg-emerald-500",
    role: "Buyer's Agent",
    joinedAt: "2020-01-12",
    metrics: { dealsClosedYTD: 5, volumeClosedYTD: 1_490_000, activeDeals: 7, pipelineValue: 1_980_000, leadsThisMonth: 14, appointmentsSet: 5, conversionRate: 17.4, avgResponseMinutes: 5 },
    trend: [4, 4, 5, 4, 6, 5, 5, 6],
    status: "steady",
    aiAdoptionScore: 70,
    aiTip: "Solid baseline — sharpen response time to break 80.",
    avatarUrl: "https://randomuser.me/api/portraits/women/55.jpg",
  },
  {
    id: "a_012",
    name: "Brandon Foster",
    initials: "BF",
    avatarColor: "bg-orange-500",
    role: "Listing Agent",
    joinedAt: "2016-11-29",
    metrics: { dealsClosedYTD: 8, volumeClosedYTD: 2_590_000, activeDeals: 10, pipelineValue: 3_320_000, leadsThisMonth: 22, appointmentsSet: 9, conversionRate: 22.8, avgResponseMinutes: 4 },
    trend: [5, 6, 5, 7, 6, 8, 7, 8],
    status: "top",
    aiAdoptionScore: 91,
    aiTip: "Top performer — share your follow-up cadence with the team.",
    avatarUrl: "https://randomuser.me/api/portraits/men/76.jpg",
  },
  {
    id: "a_013",
    name: "Sophia Russo",
    initials: "SR",
    avatarColor: "bg-fuchsia-500",
    role: "Dual",
    joinedAt: "2019-05-04",
    metrics: { dealsClosedYTD: 6, volumeClosedYTD: 1_910_000, activeDeals: 8, pipelineValue: 2_550_000, leadsThisMonth: 17, appointmentsSet: 7, conversionRate: 19.6, avgResponseMinutes: 5 },
    trend: [3, 4, 5, 5, 6, 5, 6, 7],
    status: "rising",
    aiAdoptionScore: 78,
    aiTip: "Strong rise — add BombBomb to lift conversion past 20%.",
    avatarUrl: "https://randomuser.me/api/portraits/women/26.jpg",
  },
  {
    id: "a_014",
    name: "Ethan Cohen",
    initials: "EC",
    avatarColor: "bg-yellow-500",
    role: "Buyer's Agent",
    joinedAt: "2021-08-19",
    metrics: { dealsClosedYTD: 4, volumeClosedYTD: 1_180_000, activeDeals: 6, pipelineValue: 1_640_000, leadsThisMonth: 13, appointmentsSet: 4, conversionRate: 15.2, avgResponseMinutes: 9 },
    trend: [3, 3, 4, 3, 4, 4, 5, 4],
    status: "needs-coaching",
    aiAdoptionScore: 51,
    aiTip: "Response time over team avg — start with Calendly defaults.",
    avatarUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: "a_015",
    name: "Mia Davenport",
    initials: "MD",
    avatarColor: "bg-red-500",
    role: "Listing Agent",
    joinedAt: "2015-06-08",
    metrics: { dealsClosedYTD: 9, volumeClosedYTD: 2_960_000, activeDeals: 11, pipelineValue: 3_780_000, leadsThisMonth: 24, appointmentsSet: 10, conversionRate: 23.6, avgResponseMinutes: 3 },
    trend: [5, 6, 6, 7, 8, 7, 8, 9],
    status: "top",
    aiAdoptionScore: 94,
    aiTip: "Reference performer for the team — protect your cadence.",
    avatarUrl: "https://randomuser.me/api/portraits/women/40.jpg",
  },
  {
    id: "a_016",
    name: "Jacob Ramirez",
    initials: "JR",
    avatarColor: "bg-lime-500",
    role: "Junior Agent",
    joinedAt: "2024-11-02",
    metrics: { dealsClosedYTD: 2, volumeClosedYTD: 480_000, activeDeals: 3, pipelineValue: 740_000, leadsThisMonth: 8, appointmentsSet: 3, conversionRate: 16.1, avgResponseMinutes: 6 },
    trend: [0, 1, 1, 1, 2, 2, 2, 3],
    status: "rising",
    aiAdoptionScore: 62,
    aiTip: "On a good ramp — add saved-search alerts for buyer leads.",
    avatarUrl: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: "a_017",
    name: "Ava Chen",
    initials: "AC",
    avatarColor: "bg-indigo-500",
    role: "Buyer's Agent",
    joinedAt: "2018-03-17",
    metrics: { dealsClosedYTD: 6, volumeClosedYTD: 1_690_000, activeDeals: 8, pipelineValue: 2_280_000, leadsThisMonth: 16, appointmentsSet: 7, conversionRate: 20.5, avgResponseMinutes: 5 },
    trend: [3, 4, 5, 5, 5, 6, 6, 6],
    status: "steady",
    aiAdoptionScore: 79,
    aiTip: "One step from Excellent — automate weekend lead routing.",
    avatarUrl: "https://randomuser.me/api/portraits/women/63.jpg",
  },
  {
    id: "a_018",
    name: "Logan Walsh",
    initials: "LW",
    avatarColor: "bg-blue-700",
    role: "Listing Agent",
    joinedAt: "2017-10-23",
    metrics: { dealsClosedYTD: 7, volumeClosedYTD: 2_180_000, activeDeals: 9, pipelineValue: 2_870_000, leadsThisMonth: 19, appointmentsSet: 8, conversionRate: 21.3, avgResponseMinutes: 4 },
    trend: [4, 5, 5, 6, 6, 7, 7, 7],
    status: "steady",
    aiAdoptionScore: 81,
    aiTip: "Excellent tier reached — keep your weekly review cadence.",
    avatarUrl: "https://randomuser.me/api/portraits/men/35.jpg",
  },
  {
    id: "a_019",
    name: "Isabella Schmidt",
    initials: "IS",
    avatarColor: "bg-rose-700",
    role: "Dual",
    joinedAt: "2014-02-14",
    metrics: { dealsClosedYTD: 8, volumeClosedYTD: 2_440_000, activeDeals: 10, pipelineValue: 3_180_000, leadsThisMonth: 21, appointmentsSet: 9, conversionRate: 22.0, avgResponseMinutes: 4 },
    trend: [4, 5, 6, 6, 7, 7, 8, 8],
    status: "top",
    aiAdoptionScore: 89,
    aiTip: "Top of league — your sphere blasts are the team benchmark.",
    avatarUrl: "https://randomuser.me/api/portraits/women/72.jpg",
  },
  {
    id: "a_020",
    name: "Mason Williams",
    initials: "MW",
    avatarColor: "bg-stone-500",
    role: "Buyer's Agent",
    joinedAt: "2022-04-30",
    metrics: { dealsClosedYTD: 4, volumeClosedYTD: 1_120_000, activeDeals: 6, pipelineValue: 1_560_000, leadsThisMonth: 12, appointmentsSet: 4, conversionRate: 15.8, avgResponseMinutes: 8 },
    trend: [3, 3, 3, 4, 4, 4, 5, 4],
    status: "needs-coaching",
    aiAdoptionScore: 48,
    aiTip: "Response time and conversion both lagging — pair with a top.",
    avatarUrl: "https://randomuser.me/api/portraits/men/64.jpg",
  },
  {
    id: "a_021",
    name: "Charlotte Brennan",
    initials: "CB",
    avatarColor: "bg-amber-700",
    role: "Listing Agent",
    joinedAt: "2016-08-11",
    metrics: { dealsClosedYTD: 7, volumeClosedYTD: 2_070_000, activeDeals: 9, pipelineValue: 2_690_000, leadsThisMonth: 18, appointmentsSet: 7, conversionRate: 19.8, avgResponseMinutes: 5 },
    trend: [4, 4, 5, 5, 6, 6, 7, 7],
    status: "steady",
    aiAdoptionScore: 75,
    aiTip: "Adopt automated nurture — biggest unlock for your queue.",
    avatarUrl: "https://randomuser.me/api/portraits/women/89.jpg",
  },
  {
    id: "a_022",
    name: "Carlos Rivera",
    initials: "CR",
    avatarColor: "bg-green-600",
    role: "Buyer's Agent",
    joinedAt: "2020-12-05",
    metrics: { dealsClosedYTD: 5, volumeClosedYTD: 1_330_000, activeDeals: 7, pipelineValue: 1_770_000, leadsThisMonth: 13, appointmentsSet: 5, conversionRate: 17.9, avgResponseMinutes: 6 },
    trend: [3, 4, 4, 5, 5, 5, 6, 6],
    status: "rising",
    aiAdoptionScore: 67,
    aiTip: "Add Spanish-language follow-ups for the LATAM buyer segment.",
    avatarUrl: "https://randomuser.me/api/portraits/men/85.jpg",
  },
  {
    id: "a_023",
    name: "Grace Lin",
    initials: "GL",
    avatarColor: "bg-teal-700",
    role: "Listing Agent",
    joinedAt: "2018-06-18",
    metrics: { dealsClosedYTD: 6, volumeClosedYTD: 1_810_000, activeDeals: 8, pipelineValue: 2_360_000, leadsThisMonth: 16, appointmentsSet: 6, conversionRate: 18.7, avgResponseMinutes: 5 },
    trend: [4, 4, 5, 5, 5, 6, 6, 6],
    status: "steady",
    aiAdoptionScore: 72,
    aiTip: "Steady — your bottleneck is qualifying speed, not lead flow.",
    avatarUrl: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: "a_024",
    name: "Owen McCarthy",
    initials: "OM",
    avatarColor: "bg-violet-700",
    role: "Buyer's Agent",
    joinedAt: "2023-01-07",
    metrics: { dealsClosedYTD: 3, volumeClosedYTD: 760_000, activeDeals: 5, pipelineValue: 1_080_000, leadsThisMonth: 10, appointmentsSet: 3, conversionRate: 13.2, avgResponseMinutes: 10 },
    trend: [2, 2, 3, 3, 3, 3, 4, 3],
    status: "needs-coaching",
    aiAdoptionScore: 39,
    aiTip: "Critical — start with response-time fundamentals this week.",
    avatarUrl: "https://randomuser.me/api/portraits/men/46.jpg",
  },
  {
    id: "a_025",
    name: "Lily Nakamura",
    initials: "LN",
    avatarColor: "bg-sky-700",
    role: "Junior Agent",
    joinedAt: "2025-04-01",
    metrics: { dealsClosedYTD: 1, volumeClosedYTD: 280_000, activeDeals: 3, pipelineValue: 540_000, leadsThisMonth: 7, appointmentsSet: 2, conversionRate: 12.4, avgResponseMinutes: 8 },
    trend: [0, 0, 1, 1, 1, 1, 2, 1],
    status: "rising",
    aiAdoptionScore: 55,
    aiTip: "Brand new — focus on the 5-min SMS workflow first.",
    avatarUrl: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: "a_026",
    name: "Diego Vargas",
    initials: "DV",
    avatarColor: "bg-red-700",
    role: "Listing Agent",
    joinedAt: "2017-03-25",
    metrics: { dealsClosedYTD: 7, volumeClosedYTD: 2_200_000, activeDeals: 9, pipelineValue: 2_910_000, leadsThisMonth: 19, appointmentsSet: 8, conversionRate: 20.9, avgResponseMinutes: 4 },
    trend: [4, 5, 5, 6, 6, 7, 7, 7],
    status: "steady",
    aiAdoptionScore: 83,
    aiTip: "Solid Excellent tier — your sphere conversion is the lever.",
    avatarUrl: "https://randomuser.me/api/portraits/men/93.jpg",
  },
  {
    id: "a_027",
    name: "Hannah Brooks",
    initials: "HB",
    avatarColor: "bg-emerald-700",
    role: "Dual",
    joinedAt: "2019-11-13",
    metrics: { dealsClosedYTD: 6, volumeClosedYTD: 1_770_000, activeDeals: 8, pipelineValue: 2_280_000, leadsThisMonth: 16, appointmentsSet: 6, conversionRate: 18.4, avgResponseMinutes: 6 },
    trend: [3, 4, 4, 5, 5, 5, 6, 6],
    status: "steady",
    aiAdoptionScore: 68,
    aiTip: "Closer than you think to top tier — sharpen weekend coverage.",
    avatarUrl: "https://randomuser.me/api/portraits/women/47.jpg",
  },
  {
    id: "a_028",
    name: "Adrian Singh",
    initials: "AS",
    avatarColor: "bg-orange-700",
    role: "Buyer's Agent",
    joinedAt: "2021-02-26",
    metrics: { dealsClosedYTD: 5, volumeClosedYTD: 1_410_000, activeDeals: 7, pipelineValue: 1_870_000, leadsThisMonth: 14, appointmentsSet: 5, conversionRate: 17.1, avgResponseMinutes: 6 },
    trend: [3, 4, 4, 4, 5, 5, 5, 6],
    status: "steady",
    aiAdoptionScore: 66,
    aiTip: "Standardize one nurture workflow — pick saved-search alerts.",
    avatarUrl: "https://randomuser.me/api/portraits/men/29.jpg",
  },
  {
    id: "a_029",
    name: "Zoe Robinson",
    initials: "ZR",
    avatarColor: "bg-pink-700",
    role: "Junior Agent",
    joinedAt: "2024-06-10",
    metrics: { dealsClosedYTD: 2, volumeClosedYTD: 510_000, activeDeals: 4, pipelineValue: 820_000, leadsThisMonth: 9, appointmentsSet: 3, conversionRate: 15.3, avgResponseMinutes: 7 },
    trend: [1, 1, 2, 2, 2, 2, 3, 2],
    status: "rising",
    aiAdoptionScore: 60,
    aiTip: "Solid for month 11 — turn on the BombBomb workflow next.",
    avatarUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: "a_030",
    name: "Kevin Park",
    initials: "KP",
    avatarColor: "bg-purple-700",
    role: "Listing Agent",
    joinedAt: "2018-12-19",
    metrics: { dealsClosedYTD: 7, volumeClosedYTD: 2_140_000, activeDeals: 9, pipelineValue: 2_810_000, leadsThisMonth: 18, appointmentsSet: 8, conversionRate: 21.5, avgResponseMinutes: 4 },
    trend: [4, 5, 5, 6, 6, 6, 7, 7],
    status: "rising",
    aiAdoptionScore: 86,
    aiTip: "Crossed into Excellent — focus on listing-blast cadence.",
    avatarUrl: "https://randomuser.me/api/portraits/men/72.jpg",
  },
];

const leads: Lead[] = [
  {
    id: "l_001",
    name: "Robert Chen",
    initials: "RC",
    property: "3 BR Brookline, MA",
    priceRange: "$1.2M – $1.5M",
    status: "hot",
    source: "Zillow Premier",
    assignedAgentId: "a_001",
    assignedAgentName: "Sarah Mitchell",
    lastContactAt: "2026-04-26T11:14:00Z",
    nextActionAt: "2026-04-26T18:00:00Z",
    stage: "Appointment Set",
  },
  {
    id: "l_002",
    name: "Lisa Patel",
    initials: "LP",
    property: "4 BR Newton, MA",
    priceRange: "$1.6M – $2.0M",
    status: "hot",
    source: "Follow Up Boss",
    assignedAgentId: "a_002",
    assignedAgentName: "James Carter",
    lastContactAt: "2026-04-26T08:42:00Z",
    nextActionAt: "2026-04-27T15:00:00Z",
    stage: "Qualified",
  },
  {
    id: "l_003",
    name: "David Kim",
    initials: "DK",
    property: "2 BR Condo Cambridge, MA",
    priceRange: "$780K – $920K",
    status: "warm",
    source: "Google Ads",
    assignedAgentId: "a_003",
    assignedAgentName: "Priya Shah",
    lastContactAt: "2026-04-25T14:08:00Z",
    stage: "New",
  },
  {
    id: "l_004",
    name: "Jennifer Wu",
    initials: "JW",
    property: "2 BR Somerville, MA",
    priceRange: "$640K – $780K",
    status: "hot",
    source: "Realtor.com",
    assignedAgentId: "a_004",
    assignedAgentName: "Marcus Reyes",
    lastContactAt: "2026-04-26T01:20:00Z",
    nextActionAt: "2026-04-26T17:30:00Z",
    stage: "Showing",
  },
  {
    id: "l_005",
    name: "Tom Anderson",
    initials: "TA",
    property: "5 BR Wellesley, MA",
    priceRange: "$2.4M – $2.9M",
    status: "cold",
    source: "BombBomb",
    assignedAgentId: "a_005",
    assignedAgentName: "Emma O'Brien",
    lastContactAt: "2026-04-23T16:45:00Z",
    stage: "Qualified",
  },
  {
    id: "l_006",
    name: "Olivia Brennan",
    initials: "OB",
    property: "3 BR Arlington, MA",
    priceRange: "$1.0M – $1.3M",
    status: "warm",
    source: "Mailchimp",
    assignedAgentId: "a_006",
    assignedAgentName: "Daniel Park",
    lastContactAt: "2026-04-25T19:55:00Z",
    stage: "New",
  },
];

const workflows: Workflow[] = [
  // Follow-up
  {
    id: "w_001",
    name: "Zillow speed-to-lead 5-min SMS",
    description:
      "Auto-SMS within 5 minutes of a new Zillow lead, follow-up call task to assigned agent.",
    category: "Follow-up",
    tools: ["Zillow Premier", "Follow Up Boss", "Twilio"],
    status: "performing",
    ownerAgentId: "a_001",
    lastTriggeredAt: "2026-04-26T11:48:00Z",
    triggersPerDay: 18.6,
    metrics: {
      triggered: 142,
      completed: 138,
      completionRate: 97.2,
      appointmentsCreated: 34,
      closedDeals: 6,
      revenueAttributed: 1_840_000,
      costPerLead: 48,
      roi: 4.2,
    },
    trend: [10, 12, 11, 13, 14, 15, 13, 16, 18, 17, 19, 22],
    weeklyChange: 14.6,
  },
  {
    id: "w_005",
    name: "Missed-call SMS auto-response",
    description:
      "Sends a templated SMS within 30 seconds of a missed agent call, with link to schedule.",
    category: "Follow-up",
    tools: ["Twilio", "Calendly"],
    status: "healthy",
    ownerAgentId: "a_002",
    lastTriggeredAt: "2026-04-26T09:12:00Z",
    triggersPerDay: 6.3,
    metrics: {
      triggered: 47,
      completed: 47,
      completionRate: 100,
      appointmentsCreated: 11,
      closedDeals: 2,
      revenueAttributed: 540_000,
      costPerLead: 9,
      roi: 5.8,
    },
    trend: [3, 4, 3, 5, 4, 5, 6, 5, 7, 6, 8, 7],
    weeklyChange: 4.9,
  },
  {
    id: "w_006",
    name: "Same-day appointment confirmation",
    description:
      "Reminder SMS + email 4 hours before showing or listing appointment.",
    category: "Follow-up",
    tools: ["Calendly", "Twilio", "Mailchimp"],
    status: "healthy",
    ownerAgentId: "a_001",
    lastTriggeredAt: "2026-04-26T13:00:00Z",
    triggersPerDay: 4.1,
    metrics: {
      triggered: 31,
      completed: 30,
      completionRate: 96.8,
      appointmentsCreated: 0,
      closedDeals: 4,
      revenueAttributed: 980_000,
      costPerLead: 6,
      roi: 9.2,
    },
    trend: [2, 3, 2, 3, 3, 4, 3, 4, 4, 5, 4, 5],
    weeklyChange: 8.1,
  },

  // Lead Nurture
  {
    id: "w_002",
    name: "BombBomb video follow-up",
    description:
      "Personalized video email 24h after first contact for warm leads.",
    category: "Lead Nurture",
    tools: ["BombBomb", "Follow Up Boss"],
    status: "underperforming",
    ownerAgentId: "a_003",
    lastTriggeredAt: "2026-04-26T07:25:00Z",
    triggersPerDay: 9.7,
    metrics: {
      triggered: 68,
      completed: 41,
      completionRate: 60.3,
      appointmentsCreated: 7,
      closedDeals: 1,
      revenueAttributed: 280_000,
      costPerLead: 92,
      roi: 0.8,
    },
    trend: [22, 24, 21, 19, 17, 15, 14, 12, 10, 9, 8, 7],
    weeklyChange: -34.1,
  },
  {
    id: "w_007",
    name: "Buyer guide 7-day drip",
    description:
      "Weekly market education + neighborhood spotlights for first-time buyers.",
    category: "Lead Nurture",
    tools: ["Mailchimp", "Follow Up Boss"],
    status: "performing",
    ownerAgentId: "a_002",
    lastTriggeredAt: "2026-04-26T08:00:00Z",
    triggersPerDay: 12.4,
    metrics: {
      triggered: 87,
      completed: 84,
      completionRate: 96.6,
      appointmentsCreated: 19,
      closedDeals: 4,
      revenueAttributed: 1_120_000,
      costPerLead: 14,
      roi: 5.4,
    },
    trend: [5, 6, 6, 7, 8, 9, 9, 10, 11, 12, 12, 14],
    weeklyChange: 11.2,
  },
  {
    id: "w_008",
    name: "Listing alert by saved search",
    description:
      "Daily email with new listings matching each lead's saved-search criteria.",
    category: "Lead Nurture",
    tools: ["kvCORE", "Mailchimp"],
    status: "healthy",
    ownerAgentId: "a_004",
    lastTriggeredAt: "2026-04-26T06:30:00Z",
    triggersPerDay: 22.8,
    metrics: {
      triggered: 164,
      completed: 159,
      completionRate: 97.0,
      appointmentsCreated: 12,
      closedDeals: 3,
      revenueAttributed: 870_000,
      costPerLead: 8,
      roi: 4.6,
    },
    trend: [12, 14, 13, 15, 16, 17, 16, 18, 18, 20, 19, 22],
    weeklyChange: 7.4,
  },

  // Listing
  {
    id: "w_009",
    name: "New listing blast to sphere",
    description:
      "Email + SMS to past-client database within 1 hour of going live in MLS.",
    category: "Listing",
    tools: ["Mailchimp", "Twilio", "Canva"],
    status: "performing",
    ownerAgentId: "a_005",
    lastTriggeredAt: "2026-04-25T14:22:00Z",
    triggersPerDay: 0.7,
    metrics: {
      triggered: 5,
      completed: 5,
      completionRate: 100,
      appointmentsCreated: 8,
      closedDeals: 1,
      revenueAttributed: 480_000,
      costPerLead: 22,
      roi: 7.1,
    },
    trend: [1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
    weeklyChange: 2.3,
  },
  {
    id: "w_010",
    name: "Just-sold market update",
    description:
      "Postcard + email 48h after close, sent to a 0.5-mile radius around the listing.",
    category: "Listing",
    tools: ["Canva", "Mailchimp"],
    status: "healthy",
    ownerAgentId: "a_005",
    lastTriggeredAt: "2026-04-23T16:10:00Z",
    triggersPerDay: 0.4,
    metrics: {
      triggered: 3,
      completed: 3,
      completionRate: 100,
      appointmentsCreated: 4,
      closedDeals: 0,
      revenueAttributed: 0,
      costPerLead: 41,
      roi: 2.8,
    },
    trend: [0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1],
    weeklyChange: 0,
  },

  // Re-engagement
  {
    id: "w_004",
    name: "Cold lead 90-day re-engagement",
    description:
      "Drip sequence to leads with no activity for 90+ days. SMTP failing on Mailchimp connector.",
    category: "Re-engagement",
    tools: ["kvCORE", "Mailchimp"],
    status: "broken",
    ownerAgentId: "a_004",
    lastTriggeredAt: "2026-04-08T11:32:00Z",
    triggersPerDay: 0,
    metrics: {
      triggered: 0,
      completed: 0,
      completionRate: 0,
      appointmentsCreated: 0,
      closedDeals: 0,
      revenueAttributed: 0,
      costPerLead: 0,
      roi: 0,
    },
    trend: [3, 3, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0],
    weeklyChange: -100,
  },
  {
    id: "w_011",
    name: "Stalled appointment recovery",
    description:
      "Re-engages leads who scheduled but no-showed in the last 14 days.",
    category: "Re-engagement",
    tools: ["Follow Up Boss", "Twilio"],
    status: "underperforming",
    ownerAgentId: "a_005",
    lastTriggeredAt: "2026-04-26T10:45:00Z",
    triggersPerDay: 2.0,
    metrics: {
      triggered: 14,
      completed: 11,
      completionRate: 78.6,
      appointmentsCreated: 2,
      closedDeals: 0,
      revenueAttributed: 0,
      costPerLead: 31,
      roi: 0.6,
    },
    trend: [4, 3, 3, 2, 3, 2, 2, 1, 2, 1, 2, 2],
    weeklyChange: -12.4,
  },

  // Sphere
  {
    id: "w_003",
    name: "30-day past client check-in",
    description: "Automated touchpoint to clients 30 days post-close.",
    category: "Sphere",
    tools: ["Mailchimp", "Follow Up Boss"],
    status: "healthy",
    ownerAgentId: "a_001",
    lastTriggeredAt: "2026-04-26T08:00:00Z",
    triggersPerDay: 7.7,
    metrics: {
      triggered: 54,
      completed: 52,
      completionRate: 96.3,
      appointmentsCreated: 4,
      closedDeals: 2,
      revenueAttributed: 720_000,
      costPerLead: 12,
      roi: 6.1,
    },
    trend: [4, 5, 4, 5, 5, 6, 5, 6, 6, 7, 6, 7],
    weeklyChange: 3.2,
  },
  {
    id: "w_012",
    name: "Annual home anniversary",
    description:
      "Yearly check-in with property valuation refresh + handwritten note prompt.",
    category: "Sphere",
    tools: ["Mailchimp", "Slack"],
    status: "performing",
    ownerAgentId: "a_006",
    lastTriggeredAt: "2026-04-24T07:15:00Z",
    triggersPerDay: 1.4,
    metrics: {
      triggered: 10,
      completed: 10,
      completionRate: 100,
      appointmentsCreated: 3,
      closedDeals: 1,
      revenueAttributed: 320_000,
      costPerLead: 7,
      roi: 8.4,
    },
    trend: [1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2],
    weeklyChange: 5.6,
  },
];

const insights: Insight[] = [
  // ZONE 1 — ACT NOW (critical)
  {
    id: "i_001",
    type: "critical",
    category: "Workflow",
    title: "BombBomb video follow-up dropped 34% this week",
    impact: "27 silent failures · $280K pipeline at risk",
    detail:
      "Completion rate fell from 91% to 60%. Looks like the SMTP integration with Follow Up Boss is failing on 3 of your agents (Carter, Reyes, O'Brien). Worth checking the connector status before the weekend.",
    primaryAction: { label: "Investigate now" },
    state: "pending",
    createdAt: "2026-04-28T07:30:00Z",
  },

  // ZONE 2 — THIS WEEK (warnings)
  {
    id: "i_002",
    type: "warning",
    category: "Performance",
    title: "5 hot leads aged 7+ days without contact",
    impact: "$3.4M pipeline at risk · all on Emma's queue",
    detail:
      "Median response time on Emma O'Brien's queue is 11 minutes — 2.7× team average. Five Hot leads have had no agent contact in 7+ days. Reassign now or pair her with Priya for a one-week shadow.",
    primaryAction: { label: "Reassign leads" },
    state: "pending",
    createdAt: "2026-04-28T06:15:00Z",
  },
  {
    id: "i_008",
    type: "warning",
    category: "Workflow",
    title: "23 deals stuck at Appointment Set for 14+ days",
    impact: "$8.4M frozen pipeline · avg age 22 days",
    detail:
      "These deals haven't moved past Appointment Set despite scheduled follow-ups. Pattern: buyer asked for 'time to think' and never re-engaged. A personal call from you to the top 5 by value usually breaks the freeze in this segment.",
    primaryAction: { label: "Call top 5 myself" },
    state: "pending",
    createdAt: "2026-04-27T19:30:00Z",
  },
  {
    id: "i_009",
    type: "warning",
    category: "Performance",
    title: "Priya's queue is 2× team capacity",
    impact: "28 active leads · team avg 14 · conversion -3pts wk",
    detail:
      "Priya is your top performer, but her conversion rate dropped 3 points this week — her queue is now 2× the team average. Daniel Park has bandwidth (11 active vs team target 18). Rebalancing 7-8 leads to Daniel should recover Priya's conversion.",
    primaryAction: { label: "Rebalance to Daniel" },
    state: "pending",
    createdAt: "2026-04-27T14:10:00Z",
  },
  {
    id: "i_010",
    type: "warning",
    category: "Tech Stack",
    title: "ConvertKit + Mailchimp running in parallel",
    impact: "$230/mo overlap · 1,800 duplicate contacts",
    detail:
      "Both tools have the same 1,800 contacts. ConvertKit (added Q3) is now your primary email provider, but Mailchimp is still auto-renewing. Cancel Mailchimp at the next cycle to save $2,760/year — no contact loss.",
    primaryAction: { label: "Cancel Mailchimp" },
    state: "pending",
    createdAt: "2026-04-27T10:00:00Z",
  },
  {
    id: "i_003",
    type: "warning",
    category: "Marketing",
    title: "Google Ads spend up 22% with no lead lift",
    impact: "+$870/wk · lead volume flat (89 → 89)",
    detail:
      "Google Ads spent $4,820 this week vs $3,950 last week, but lead volume hasn't moved. Worth a 30-min audit of the campaign mix — likely a few CPC outliers eating budget.",
    primaryAction: { label: "Review spend" },
    state: "pending",
    createdAt: "2026-04-26T18:00:00Z",
  },
  {
    id: "i_006",
    type: "warning",
    category: "Performance",
    title: "Coach Emma on response-time discipline",
    impact: "11.4 min median · 2.7× team avg · -3 appts/wk",
    detail:
      "Emma's queue is bleeding appointments. Suggested coaching: a 30-min 1:1 plus a one-week shadow paired with Priya (your top responder). The most actionable lever this month for her output.",
    primaryAction: { label: "Schedule 1:1" },
    state: "pending",
    createdAt: "2026-04-25T16:20:00Z",
  },

  // ZONE 3 — WORTH KNOWING (opportunities + info)
  {
    id: "i_004",
    type: "opportunity",
    category: "Workflow",
    title: "Zillow speed-to-lead drove 2.4× more appointments",
    impact: "34 appts / 142 leads · 4.2× ROI",
    detail:
      "The 5-min SMS workflow is outperforming the prior cadence by 2.4× on appointment-set rate. Consider rolling out to Realtor.com leads where you already see speed gaps.",
    primaryAction: { label: "Scale to Realtor.com" },
    state: "pending",
    createdAt: "2026-04-26T22:48:00Z",
  },
  {
    id: "i_011",
    type: "opportunity",
    category: "Marketing",
    title: "Saturday 10am sphere emails get 3× the open rate",
    impact: "62% open vs 21% midweek · 4-week consistent pattern",
    detail:
      "Last 4 Saturdays at 10–11am: sphere blast emails averaged 62% open rate, vs 21% on Tuesday/Wednesday. The pattern holds across content type. Lock the schedule into your standard cadence.",
    primaryAction: { label: "Reschedule cadence" },
    state: "pending",
    createdAt: "2026-04-26T11:00:00Z",
  },
  {
    id: "i_012",
    type: "opportunity",
    category: "Lead Gen",
    title: "8 buyer leads have signaled seller intent",
    impact: "$11.2M potential listing volume · CRM-flagged",
    detail:
      "These 8 active buyers either mentioned 'we'll need to sell our current home' in CRM notes, or set up a Zillow saved search for their own neighborhood. Convert each into a buyer-and-seller engagement letter — typical lift on this segment is 2.1× LTV.",
    primaryAction: { label: "Review the 8 leads" },
    state: "pending",
    createdAt: "2026-04-25T15:20:00Z",
  },
  {
    id: "i_013",
    type: "opportunity",
    category: "Lead Gen",
    title: "Brookline showings up 40% MoM — 3 agents not active",
    impact: "+12 showings/week · Sarah, James, Marcus uninvolved",
    detail:
      "Brookline activity is heating up: showing requests up 40% month-over-month. Currently only Priya and Emma are taking those leads. Routing more to Sarah, James, and Marcus would catch the surge before Compass and Coldwell do.",
    primaryAction: { label: "Adjust routing" },
    state: "pending",
    createdAt: "2026-04-24T09:30:00Z",
  },
  {
    id: "i_005",
    type: "info",
    category: "Performance",
    title: "Daniel Park is on track to hit ramp targets",
    impact: "17.5% conversion · vs 14% benchmark for new hires",
    detail:
      "First-year agent, month 8. Converting at 17.5% — above the 14% benchmark for new hires. A public callout in the team Slack would land well right now.",
    primaryAction: { label: "Send recognition" },
    state: "pending",
    createdAt: "2026-04-24T11:30:00Z",
  },
  {
    id: "i_014",
    type: "info",
    category: "Performance",
    title: "Monday discovery calls have a 60% no-show rate",
    impact: "Tue/Wed slots close 1.4× more often",
    detail:
      "Last 90 days: Monday morning discovery calls average 60% no-show, vs 18% for Tuesday and Wednesday afternoon. Likely cause: weekend re-shopping by the buyer. Consider blocking Mondays from the team Calendly defaults.",
    primaryAction: { label: "Update Calendly" },
    state: "pending",
    createdAt: "2026-04-23T13:00:00Z",
  },
  {
    id: "i_007",
    type: "info",
    category: "Marketing",
    title: "Realtor.com Pro converts 4× lower than Zillow",
    impact: "4.2% vs 18% · $1,890/mo cost",
    detail:
      "Realtor.com Pro renewal is up next month. ROI is 4× worse than Zillow Premier on the same spend window. Worth pausing or downgrading before renewal.",
    primaryAction: { label: "Review contract" },
    state: "pending",
    createdAt: "2026-04-22T14:30:00Z",
  },
];

export const dashboardData: DashboardData = {
  user,
  period,
  kpis,
  insights,
  agents,
  leads,
  workflows,
  pipelineTrend,
  leadsBySource,
  pipelineByStage,
  completionRateTrend,
  teamProductionTrend,
};
