import type {
  Agent,
  CategoryPoint,
  DashboardData,
  Insight,
  KPI,
  Lead,
  TimeseriesPoint,
  User,
  Workflow,
} from "./types";

const user: User = {
  id: "u_001",
  name: "Maria Gonzalez",
  initials: "MG",
  role: "Team Leader",
  email: "maria@gonzalezteam.com",
  teamName: "Gonzalez Team",
};

const period = {
  start: "2026-04-21",
  end: "2026-04-27",
  label: "Apr 21 – 27, 2026",
};

const kpis: KPI[] = [
  {
    id: "active-deals",
    label: "Active Deals",
    value: "47",
    rawValue: 47,
    hint: "$14.2M pipeline",
    iconKey: "deals",
    tone: "primary",
    trend: [38, 41, 39, 43, 45, 44, 47, 47],
    delta: { value: 12.4, period: "vs last week" },
  },
  {
    id: "new-leads",
    label: "New Leads",
    value: "89",
    rawValue: 89,
    hint: "this week",
    iconKey: "leads",
    tone: "success",
    trend: [72, 76, 79, 82, 85, 84, 87, 89],
    delta: { value: 8.1, period: "vs last week" },
  },
  {
    id: "lead-to-appt",
    label: "Lead to Appointment",
    value: "18.4%",
    rawValue: 18.4,
    hint: "30-day rolling",
    iconKey: "appointment",
    tone: "warning",
    trend: [20.1, 19.4, 19.2, 19.0, 18.9, 18.6, 18.5, 18.4],
    delta: { value: -2.1, period: "vs last month" },
  },
  {
    id: "response-time",
    label: "Avg Response Time",
    value: "3m 22s",
    rawValue: 202,
    hint: "first touch",
    iconKey: "response-time",
    tone: "danger",
    trend: [5.8, 5.4, 5.0, 4.7, 4.5, 4.2, 3.6, 3.4],
    delta: { value: -40.2, period: "vs last week", inverted: true },
  },
];

const pipelineTrend: TimeseriesPoint[] = [
  { label: "Feb 03", value: 9_800_000 },
  { label: "Feb 10", value: 10_400_000 },
  { label: "Feb 17", value: 10_100_000 },
  { label: "Feb 24", value: 11_200_000 },
  { label: "Mar 03", value: 10_800_000 },
  { label: "Mar 10", value: 11_900_000 },
  { label: "Mar 17", value: 12_400_000 },
  { label: "Mar 24", value: 11_700_000 },
  { label: "Mar 31", value: 12_800_000 },
  { label: "Apr 07", value: 13_500_000 },
  { label: "Apr 14", value: 13_100_000 },
  { label: "Apr 21", value: 14_200_000 },
];

const leadsBySource: CategoryPoint[] = [
  { label: "Zillow Premier", value: 28 },
  { label: "Follow Up Boss", value: 22 },
  { label: "Google Ads", value: 14 },
  { label: "Realtor.com", value: 11 },
  { label: "BombBomb", value: 8 },
  { label: "Mailchimp", value: 6 },
];

const pipelineByStage: CategoryPoint[] = [
  { label: "New", value: 18, secondary: 5_400_000, color: "#94a3b8" },
  { label: "Qualified", value: 12, secondary: 3_600_000, color: "#0ea5e9" },
  { label: "Appointment Set", value: 8, secondary: 2_400_000, color: "#f59e0b" },
  { label: "Showing", value: 5, secondary: 1_500_000, color: "#7c3aed" },
  { label: "Offer", value: 3, secondary: 900_000, color: "#10b981" },
  { label: "Under Contract", value: 1, secondary: 400_000, color: "#059669" },
];

const agents: Agent[] = [
  {
    id: "a_001",
    name: "Sarah Mitchell",
    initials: "SM",
    avatarColor: "bg-violet-500",
    role: "Listing Agent",
    joinedAt: "2021-03-15",
    metrics: {
      dealsClosedYTD: 8,
      volumeClosedYTD: 2_410_000,
      activeDeals: 11,
      pipelineValue: 3_850_000,
      leadsThisMonth: 24,
      appointmentsSet: 9,
      conversionRate: 22.4,
      avgResponseMinutes: 4,
    },
    trend: [3, 5, 4, 6, 7, 5, 8, 8],
    status: "top",
  },
  {
    id: "a_002",
    name: "James Carter",
    initials: "JC",
    avatarColor: "bg-emerald-500",
    role: "Buyer's Agent",
    joinedAt: "2020-08-02",
    metrics: {
      dealsClosedYTD: 7,
      volumeClosedYTD: 2_120_000,
      activeDeals: 9,
      pipelineValue: 2_940_000,
      leadsThisMonth: 19,
      appointmentsSet: 7,
      conversionRate: 19.1,
      avgResponseMinutes: 6,
    },
    trend: [4, 4, 5, 6, 5, 7, 6, 7],
    status: "steady",
  },
  {
    id: "a_003",
    name: "Priya Shah",
    initials: "PS",
    avatarColor: "bg-amber-500",
    role: "Dual",
    joinedAt: "2022-01-20",
    metrics: {
      dealsClosedYTD: 6,
      volumeClosedYTD: 1_840_000,
      activeDeals: 8,
      pipelineValue: 2_310_000,
      leadsThisMonth: 17,
      appointmentsSet: 8,
      conversionRate: 24.0,
      avgResponseMinutes: 3,
    },
    trend: [2, 3, 4, 5, 5, 6, 6, 6],
    status: "rising",
  },
  {
    id: "a_004",
    name: "Marcus Reyes",
    initials: "MR",
    avatarColor: "bg-sky-500",
    role: "Buyer's Agent",
    joinedAt: "2019-11-04",
    metrics: {
      dealsClosedYTD: 5,
      volumeClosedYTD: 1_510_000,
      activeDeals: 7,
      pipelineValue: 2_080_000,
      leadsThisMonth: 14,
      appointmentsSet: 5,
      conversionRate: 16.0,
      avgResponseMinutes: 8,
    },
    trend: [5, 4, 4, 6, 5, 4, 5, 5],
    status: "steady",
  },
  {
    id: "a_005",
    name: "Emma O'Brien",
    initials: "EO",
    avatarColor: "bg-rose-500",
    role: "Listing Agent",
    joinedAt: "2018-06-12",
    metrics: {
      dealsClosedYTD: 5,
      volumeClosedYTD: 1_390_000,
      activeDeals: 6,
      pipelineValue: 1_780_000,
      leadsThisMonth: 12,
      appointmentsSet: 4,
      conversionRate: 14.2,
      avgResponseMinutes: 11,
    },
    trend: [6, 6, 5, 4, 4, 4, 5, 5],
    status: "needs-coaching",
    coachingNote:
      "Response time slipped above 10 min — review BombBomb cadence and lead routing.",
  },
  {
    id: "a_006",
    name: "Daniel Park",
    initials: "DP",
    avatarColor: "bg-teal-500",
    role: "Junior Agent",
    joinedAt: "2024-09-01",
    metrics: {
      dealsClosedYTD: 3,
      volumeClosedYTD: 820_000,
      activeDeals: 5,
      pipelineValue: 1_240_000,
      leadsThisMonth: 11,
      appointmentsSet: 4,
      conversionRate: 17.5,
      avgResponseMinutes: 5,
    },
    trend: [1, 2, 2, 3, 3, 3, 3, 3],
    status: "rising",
  },
];

const leads: Lead[] = [
  {
    id: "l_001",
    name: "Robert Chen",
    initials: "RC",
    property: "3 BR Brookline, MA",
    priceRange: "$1.2M – $1.5M",
    status: "hot",
    source: "Zillow Premier",
    assignedAgentId: "a_001",
    assignedAgentName: "Sarah Mitchell",
    lastContactAt: "2026-04-26T11:14:00Z",
    nextActionAt: "2026-04-26T18:00:00Z",
    stage: "Appointment Set",
  },
  {
    id: "l_002",
    name: "Lisa Patel",
    initials: "LP",
    property: "4 BR Newton, MA",
    priceRange: "$1.6M – $2.0M",
    status: "hot",
    source: "Follow Up Boss",
    assignedAgentId: "a_002",
    assignedAgentName: "James Carter",
    lastContactAt: "2026-04-26T08:42:00Z",
    nextActionAt: "2026-04-27T15:00:00Z",
    stage: "Qualified",
  },
  {
    id: "l_003",
    name: "David Kim",
    initials: "DK",
    property: "2 BR Condo Cambridge, MA",
    priceRange: "$780K – $920K",
    status: "warm",
    source: "Google Ads",
    assignedAgentId: "a_003",
    assignedAgentName: "Priya Shah",
    lastContactAt: "2026-04-25T14:08:00Z",
    stage: "New",
  },
  {
    id: "l_004",
    name: "Jennifer Wu",
    initials: "JW",
    property: "2 BR Somerville, MA",
    priceRange: "$640K – $780K",
    status: "hot",
    source: "Realtor.com",
    assignedAgentId: "a_004",
    assignedAgentName: "Marcus Reyes",
    lastContactAt: "2026-04-26T01:20:00Z",
    nextActionAt: "2026-04-26T17:30:00Z",
    stage: "Showing",
  },
  {
    id: "l_005",
    name: "Tom Anderson",
    initials: "TA",
    property: "5 BR Wellesley, MA",
    priceRange: "$2.4M – $2.9M",
    status: "cold",
    source: "BombBomb",
    assignedAgentId: "a_005",
    assignedAgentName: "Emma O'Brien",
    lastContactAt: "2026-04-23T16:45:00Z",
    stage: "Qualified",
  },
  {
    id: "l_006",
    name: "Olivia Brennan",
    initials: "OB",
    property: "3 BR Arlington, MA",
    priceRange: "$1.0M – $1.3M",
    status: "warm",
    source: "Mailchimp",
    assignedAgentId: "a_006",
    assignedAgentName: "Daniel Park",
    lastContactAt: "2026-04-25T19:55:00Z",
    stage: "New",
  },
];

const workflows: Workflow[] = [
  {
    id: "w_001",
    name: "Zillow speed-to-lead 5-min SMS",
    description:
      "Auto-SMS within 5 minutes of a new Zillow lead, follow-up call task to assigned agent.",
    category: "Follow-up",
    tools: ["Zillow Premier", "Follow Up Boss"],
    status: "performing",
    metrics: {
      triggered: 142,
      completed: 138,
      completionRate: 97.2,
      appointmentsCreated: 34,
      closedDeals: 6,
      revenueAttributed: 1_840_000,
      costPerLead: 48,
      roi: 4.2,
    },
    trend: [10, 12, 11, 13, 14, 15, 13, 16, 18, 17, 19, 22],
    weeklyChange: 14.6,
  },
  {
    id: "w_002",
    name: "BombBomb video follow-up",
    description: "Personalized video email 24h after first contact for warm leads.",
    category: "Lead Nurture",
    tools: ["BombBomb", "Follow Up Boss"],
    status: "underperforming",
    metrics: {
      triggered: 68,
      completed: 41,
      completionRate: 60.3,
      appointmentsCreated: 7,
      closedDeals: 1,
      revenueAttributed: 280_000,
      costPerLead: 92,
      roi: 0.8,
    },
    trend: [22, 24, 21, 19, 17, 15, 14, 12, 10, 9, 8, 7],
    weeklyChange: -34.1,
  },
  {
    id: "w_003",
    name: "30-day past client check-in",
    description: "Automated touchpoint to clients 30 days post-close.",
    category: "Sphere",
    tools: ["Mailchimp", "Follow Up Boss"],
    status: "healthy",
    metrics: {
      triggered: 54,
      completed: 52,
      completionRate: 96.3,
      appointmentsCreated: 4,
      closedDeals: 2,
      revenueAttributed: 720_000,
      costPerLead: 12,
      roi: 6.1,
    },
    trend: [4, 5, 4, 5, 5, 6, 5, 6, 6, 7, 6, 7],
    weeklyChange: 3.2,
  },
  {
    id: "w_004",
    name: "Cold lead 90-day re-engagement",
    description: "Drip sequence to leads with no activity for 90+ days.",
    category: "Re-engagement",
    tools: ["kvCORE", "Mailchimp"],
    status: "broken",
    metrics: {
      triggered: 0,
      completed: 0,
      completionRate: 0,
      appointmentsCreated: 0,
      closedDeals: 0,
      revenueAttributed: 0,
      costPerLead: 0,
      roi: 0,
    },
    trend: [3, 3, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0],
    weeklyChange: -100,
  },
];

const insights: Insight[] = [
  {
    id: "i_001",
    priority: "critical",
    title: "BombBomb video follow-up dropped 34% this week",
    description:
      "Completion rate fell from 91% to 60%. Looks like the SMTP integration with Follow Up Boss is failing on 3 of your agents.",
    evidence: "68 triggered · 41 completed · 27 silent failures",
    primaryAction: { label: "Investigate", intent: "investigate" },
    secondaryAction: { label: "Dismiss", intent: "dismiss" },
    state: "pending",
    createdAt: "2026-04-26T07:30:00Z",
    category: "Workflow",
  },
  {
    id: "i_002",
    priority: "warning",
    title: "5 hot leads aged 7+ days without contact",
    description:
      "All 5 are assigned to Emma O'Brien. Median response time on her queue is 11 minutes — 2.7x team average.",
    evidence: "$3.4M combined pipeline at risk",
    primaryAction: { label: "Reassign leads", intent: "implement" },
    secondaryAction: { label: "View leads", intent: "details" },
    state: "pending",
    createdAt: "2026-04-26T06:15:00Z",
    category: "Pipeline",
  },
  {
    id: "i_003",
    priority: "success",
    title: "New Zillow speed-to-lead drove 2.4x more appointments",
    description:
      "5-minute SMS workflow is outperforming your prior cadence by 2.4x on appointment-set rate. Consider rolling out to Realtor.com leads.",
    evidence: "34 appointments from 142 leads · ROI 4.2x",
    primaryAction: { label: "Scale to Realtor.com", intent: "scale" },
    secondaryAction: { label: "View workflow", intent: "details" },
    state: "pending",
    createdAt: "2026-04-25T22:48:00Z",
    category: "Workflow",
  },
  {
    id: "i_004",
    priority: "warning",
    title: "Google Ads spend up 22% with no lead lift",
    description:
      "$4,820 spent this week (up from $3,950) but lead volume is flat. Worth a 30-min review of the campaign mix.",
    primaryAction: { label: "Review spend", intent: "view" },
    secondaryAction: { label: "Dismiss", intent: "dismiss" },
    state: "pending",
    createdAt: "2026-04-25T18:00:00Z",
    category: "Spend",
  },
  {
    id: "i_005",
    priority: "neutral",
    title: "Daniel Park is on track to hit ramp targets",
    description:
      "First-year agent at month 8 — converting 17.5% of leads vs 14% team benchmark for new hires. Worth a public callout.",
    primaryAction: { label: "Send recognition", intent: "implement" },
    state: "pending",
    createdAt: "2026-04-25T11:30:00Z",
    category: "Agent",
  },
];

export const dashboardData: DashboardData = {
  user,
  period,
  kpis,
  insights,
  agents,
  leads,
  workflows,
  pipelineTrend,
  leadsBySource,
  pipelineByStage,
};
